### ISSUE TITLE
04-27 To-do List

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#1]
today workList

**Comment by minsung0628** [comment]
[http://miraes.co.kr/product/%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8-%EC%9E%90%EB%8F%99%EC%B0%A8%ED%82%A4%ED%8A%B8b%ED%98%95/17394/](url) 아두이노 자동차 B타입

**Comment by ChaehwanLee** [comment]
자동차 관련 참고 autonomous car refer - https://youtu.be/dS4-qgUByy4

**Comment by minsung0628** [comment]
[http://miraes.co.kr/product/%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8-%EC%9E%90%EB%8F%99%EC%B0%A8%ED%82%A4%ED%8A%B8b%ED%98%95/17394/](url) 아두이노 자동차 B타입

**Comment by minsung0628** [comment]
아두이노 자동차 B타입 -http://miraes.co.kr/product/%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8-%EC%9E%90%EB%8F%99%EC%B0%A8%ED%82%A4%ED%8A%B8b%ED%98%95/17394/

**Comment by deepDark2** [comment]
https://docs.google.com/document/d/1xxr2f3yGGx7rId-788glnKZvJHw1qTh6U0MxFwSPnmU/edit
에서 문서 수정
https://www.youtube.com/watch?v=3a-bE1VlaU8 영상 공유(자동차 만들기)

깃허브 참여

**Comment by jinu12** [comment]
write docs -- 팀명, 계획, 역할, 주제 선정배경 또는 이유,시장 조사
[https://docs.google.com/document/d/1xxr2f3yGGx7rId-788glnKZvJHw1qTh6U0MxFwSPnmU/edit?userstoinvite=kindgivum@gmail.com&actionButton=1#](url)

**Comment by paramore0** [comment]
https://docs.google.com/document/d/1xxr2f3yGGx7rId-788glnKZvJHw1qTh6U0MxFwSPnmU/
에서 문서 수정
