### ISSUE TITLE
웹 안드로이드 테스트 및 안드로이드 ui 구현

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#19]

**Comment by jinu12** [comment]
erdAndFlowChart

![erdAndFlowChart](https://user-images.githubusercontent.com/73889507/167539206-9195e9bc-f63e-4c51-9195-25f4a0656851.png)

**Comment by jinu12** [comment]
- [ ] 웹에서 온도 습도 이산화탄소 카메라 데이터 보여주기
- [ ] 안드로이드 ui 구현
- [ ] 차 아두이노에서 mqtt로 변환

**Comment by paramore0** [comment]
`
![중간체크1](https://user-images.githubusercontent.com/99372065/167581917-90c664c6-9132-4e61-a2a4-d5b2cb5a252a.png)
`
ui 구축

**Comment by minsung0628** [comment]
https://blog.naver.com/chandong83/221156273595

**Comment by jinu12** [comment]
https://github.com/fireEmergencyControl/zeroFire/pull/24
#24 by [jinu12](https://github.com/fireEmergencyControl/zeroFire/issues?q=is%3Apr+author%3Ajinu12) was merged 19 minutes ago

https://github.com/fireEmergencyControl/zeroFire/pull/23
#23 by [ChaehwanLee](https://github.com/fireEmergencyControl/zeroFire/issues?q=is%3Apr+author%3AChaehwanLee) was merged 22 minutes ago

https://github.com/fireEmergencyControl/zeroFire/pull/22
#22 by [minsung0628](https://github.com/fireEmergencyControl/zeroFire/issues?q=is%3Apr+author%3Aminsung0628) was merged 25 minutes ago

https://github.com/fireEmergencyControl/zeroFire/pull/21
#21 by [paramore0](https://github.com/fireEmergencyControl/zeroFire/issues?q=is%3Apr+author%3Aparamore0) was merged 25 minutes ago

https://github.com/fireEmergencyControl/zeroFire/pull/20
#20 by [deepDark2](https://github.com/fireEmergencyControl/zeroFire/issues?q=is%3Apr+author%3AdeepDark2) was merged 1 hour ago

**Comment by ChaehwanLee** [comment]
참조링크

https://www.devicemart.co.kr/goods/view?no=10916352#goods_file

https://www.youtube.com/watch?v=LQjKPTiowso

https://blog.naver.com/icbanq/221813989297

https://blog.naver.com/icbanq/221794419953

https://return-value.tistory.com/76
