### ISSUE TITLE
안드로이드 메시지 mqtt 및 웹 로그인 기능 회원가입 구현 센서 mqtt, 자동차 센서 mqtt로 브로커에게 전달

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#25]

**Comment by jinu12** [comment]
- [ ] 안드로이드 mqtt 브로커에 움직임 mqtt 전달하기
- [ ] 로그인 회원가입 기능 구현
- [ ] 센서데이터를 웹페이지 구현
- [ ] 자동차 블루투스 기능 구현
- [ ] 불꽃감지센서 및 물높이 센서 mqtt 전달

**Comment by jinu12** [comment]
https://www.chartjs.org/docs/latest/charts/line.html

**Comment by ChaehwanLee** [comment]
https://onito.github.io/raspberry-pi/2018/06/30/raspberry_water_sensor/

https://heysolve.net/ko/raspberry-pi%EB%A1%9C-%EC%88%98%EC%95%95-%EB%B0%8F-%EC%88%98%EC%9C%84-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B5%AC%EC%B6%95

https://shopping.interpark.com/product/productInfo.do?prdNo=4278054387&uaTp=1&

https://github.com/juunini2/raspberrypi/blob/master/Python/20.FLUID_MCP3008.py

https://m.blog.naver.com/tiled12/221802428223

**Comment by minsung0628** [comment]
https://eduino.kr/product/detail.html?product_no=504&gclid=CjwKCAjwve2TBhByEiwAaktM1Ke0DFZpqxjWhT0TsYIhms206VlDi2QOW5HNeKl6UIVFA-XGPSDlIxoCcyQQAvD_BwE
- 불꽃감지 센서 : 모듈없이

**Comment by paramore0** [comment]
![image](https://user-images.githubusercontent.com/99372065/167811203-0891561a-d434-4193-bc87-33e90f02967a.png)
그래프 추가중입니다

**Comment by jinu12** [comment]
![오늘 내용](https://user-images.githubusercontent.com/73889507/167813043-ef3e064e-27e3-40fc-94b9-f40c6dfda648.PNG)
웹에서 tamp api 및 차트 api 구현

**Comment by deepDark2** [comment]
회원가입 및 로그인 기능을 데이터베이스와 연동해서 구현

![register1](https://user-images.githubusercontent.com/99372311/167816616-be3fd35b-db16-4320-8ede-94778cffb069.jpg)
-회원 가입시 기입한 정보가 데이터베이스에 저장
-오입력 및 미입력 방치 처리
-id 중복시 가입 실패 처리

![db1](https://user-images.githubusercontent.com/99372311/167816870-07ddf340-fcf0-45a7-bbd6-67d2801397cc.jpg)
-DB에 저장된 회원가입 정보, rno는 rank number로 rankdata 테이블의 rno 정보를 참조
-mno는 auto increment를 적용

![login1](https://user-images.githubusercontent.com/99372311/167817400-822addd6-6ba1-4a8b-b9c7-2ca97ef2e0a8.jpg)
-가입시 입력한 정보등 중 id와 패스워드를 비교해서 일치하면 로그인 성공 처리
-session id에 id를 등록
-실패시 alert 창이 뜨도록 처리

![registerfail](https://user-images.githubusercontent.com/99372311/167817780-f6c0c751-c032-4fca-936c-3adf0d02d217.jpg)
-가입 실패시 나타나는 alert 창

![loginfail](https://user-images.githubusercontent.com/99372311/167817881-51ca366c-1e97-4b1e-8911-b1cf385fa605.jpg)
-로그인 실패시 나타나는 alert 창

**Comment by jinu12** [comment]
![경로및 습도](https://user-images.githubusercontent.com/73889507/167965460-353e6409-068f-4184-97df-fce757ace793.PNG)
경로 및 습도 구현

### 에러 
화면을 가져가야 온도가 나옴
온습도와 카메라 스트리밍이 안됨
