### ISSUE TITLE
안드로이드 메시지 mqtt, 집 모형 만들기, 웹 구현

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#28]

**Comment by jinu12** [comment]
- [ ] 센서데이터를 웹페이지 구현
- [ ] 자동차 블루투스 기능 구현
- [ ] 불꽃감지센서 및 물높이 센서 mqtt 전달

**Comment by jinu12** [comment]
![자동차](https://user-images.githubusercontent.com/73889507/167966471-a0904ca4-06d6-4ac9-b7dd-2f6af169a7dc.png)
소방차 시스템 설계

**Comment by jinu12** [comment]
![zerofile (3)](https://user-images.githubusercontent.com/73889507/167989718-184f24c1-9422-4995-a515-aae71dee6da1.png)
점검 계시판, 댓글 추가

**Comment by ChaehwanLee** [comment]
- cardboard model house refer

https://www.youtube.com/watch?v=rYo2BCAavys

https://www.ehow.com/how_4810344_mosque-cardboard-box.html

**Comment by paramore0** [comment]
![image](https://user-images.githubusercontent.com/99372065/168033547-097e575d-9478-467c-9e85-733d1b016a33.png)
컨트롤탭 액티비티 mqtt 활성화

**Comment by jinu12** [comment]
불꽃감지센서로 브로커에서 fire 메시지를 전달받으면 브로커에서 실행 및 mqtt 수정

**Comment by deepDark2** [comment]
[board 테이블과 reply 테이블을 새롭게 추가]

![zf_db board](https://user-images.githubusercontent.com/99372311/168035663-d314cfa2-0a75-4e94-b09c-e9fbc8b0e318.jpg)
-board 테이블
-bno : board number, auto increment
-mno : manager number, manager 테이블의 mno 정보를 참조하는 foreign key

![zf_cb reply](https://user-images.githubusercontent.com/99372311/168035754-60e74e5f-7263-4c31-ac85-cbf25bb35347.jpg)
-reply 테이블
-rno : reply number, auto increment
-cno : board테이블의 bno 정보를 참조하는 foreign key

[안드로이드 개발 환경 구축]

![and_rest](https://user-images.githubusercontent.com/99372311/168037028-3e6e77bd-4a13-43fa-a59a-ee307b59c35d.jpg)

구축된 환경에서 manager 테이블의 정보를 json으로 변환해 웹 화면에 출력 테스트

![zf_db json](https://user-images.githubusercontent.com/99372311/168037706-66bc3b8e-182c-4485-a993-33d662249ed0.jpg)
-추후 안드로이드 환경에서 로그인 용으로 활용할 예정
