### ISSUE TITLE
차 구현, gps 센서, 안드로이드 오류, 관리자 업데이트

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#36]

**Comment by jinu12** [comment]
https://sparklers-the-makers.github.io/blog/robotics/use-neo-6m-module-with-raspberry-pi/
gps 테스트

**Comment by minsung0628** [comment]
자동차 제어 테스트(좌회전,우회전 등이 제자리에서 되고 앞으로 전진과 동시에는 에러),
 라즈베리파이를 휴대용 배터리에 연결했을 때 서브모터,쿨링팬, 수중모터 등을 연결하면 부팅이 안됨(전력문제인지 라즈베리파이 문제인지 불명..)
서브모터 제어는 2개를 상하, 좌우로 나누어서 계획

**Comment by jinu12** [comment]
https://sparklers-the-makers.github.io/blog/robotics/use-neo-6m-module-with-raspberry-pi/

**Comment by paramore0** [comment]
![image](https://user-images.githubusercontent.com/99372065/168242319-cfc1eb63-f5ef-41b9-8cd4-8ed3f4f2286b.png)
컨트롤 / 회원가입 탭 수정

**Comment by deepDark2** [comment]
[회원 정보 수정 및 실패 페이지 추가]

수정 페이지
![make change info](https://user-images.githubusercontent.com/99372311/168243133-fff8ad82-9ab9-403a-8ba5-c4b1d8c30803.jpg)

실패 페이지
![access error](https://user-images.githubusercontent.com/99372311/168243819-34aa83a9-563f-4499-99d9-d11c33096ac3.jpg)


-정보 정상 기입시에도 실패 페이지로 넘어가는 오류가 발생
-추후 해결 예정

**Comment by ChaehwanLee** [comment]
- house model blue print

![IMG_4845](https://user-images.githubusercontent.com/86588359/168247144-37a5ed96-dee2-4267-9b42-3e6579699746.jpg)
