### ISSUE TITLE
중간 종합 테스트 및 이전 구현 작업 진행

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#40]
- [ ] 1시 중간 테스트
- [x] 서브 모터와 물 펌프를 이용해 소화전 이동, 물높이 센서, 
- [ ] 2층 모형 만들기
- [ ] 자동차 gps 통신
- [ ] 안드로이드 자동차 영상 화면 출력
- [x] 관리자 페이지 삭제 및 업데이트 실행

**Comment by ChaehwanLee** [comment]
- 모형
![Uploading D0633A37-A1E9-479F-B252-43BB6C0E1676.jpeg…]()

**Comment by jinu12** [comment]
https://user-images.githubusercontent.com/73889507/168414933-c01cd185-133b-47eb-9192-0e3f4eb453e8.mp4

**Comment by ChaehwanLee** [comment]
- Car model
![image2](https://user-images.githubusercontent.com/86588359/168416030-f0f4cd54-2c05-4fa9-a04f-28933495c8cb.jpeg)
![image0](https://user-images.githubusercontent.com/86588359/168416032-d2377fd0-d91d-4504-a0aa-b2f879e6441b.jpeg)
![image1](https://user-images.githubusercontent.com/86588359/168416033-86bca41a-aecb-44df-a300-5a059487db40.jpeg)

**Comment by deepDark2** [comment]
[현재 작업 현황]

페이지 구축
-회원가입 페이지
-로그인 페이지
-회원정보 수정 페이지
-테이블 페이지 -> 미완성

웹 기능 구현
-회원 가입시 정보 저장
-로그인시 session id 등록
-로그아웃시 session id 초기화
-로그아웃 상태에서 정보조회 및 회원 탈퇴시 해당 작업을 못하도록 조치
-로그인 상태에서 다시 로그인 하지 못하도록 조치
-회원 정보를 DB에서 불러와 조회 가능하고 수정 페이지에서 수정 가능
-회원 탈퇴시 해당 id의 회원 정보를 DB에서 삭제

![login page](https://user-images.githubusercontent.com/99372311/168416487-7d7d209e-5e70-4304-ad2f-e293a23dede6.jpg)

![register page](https://user-images.githubusercontent.com/99372311/168416498-da4fbbda-59e8-4cfa-9ccb-a47f68002adb.jpg)

![info page](https://user-images.githubusercontent.com/99372311/168416530-15a832b6-d609-4296-b317-11e386252ecc.jpg)
-Change Information 버튼은 회원정보 수정 페이지로 이동
-Delete User 버튼은 회원 탈퇴(DB에서 삭제)

![change page](https://user-images.githubusercontent.com/99372311/168416516-7fd5d650-b9b8-4636-a47e-ab6daff2ddd6.jpg)
-계급은 함부로 수정 못하도록 조치

![tables page](https://user-images.githubusercontent.com/99372311/168416580-9e36d0fb-c953-41cd-8eb4-277903d8cbed.jpg)
-형태만 잡아놓은 상태. 페이지 관련 기능 추가 예정

**Comment by jinu12** [comment]
[zerofileppt.pptx](https://github.com/fireEmergencyControl/zeroFire/files/8694433/zerofileppt.pptx)

**Comment by deepDark2** [comment]
[tables 페이지에 대한 기능 구현]

![tables page](https://user-images.githubusercontent.com/99372311/168501335-cdd1d2d7-1b55-45a4-8471-5b8b3c2b56a2.jpg)
-테스트용 게시글 10개 이상을 데이터베이스에 등록
-10개 단위로 페이지에 보여주도록 기능 구현

![tables db](https://user-images.githubusercontent.com/99372311/168501406-a0f127d4-e56a-46db-80d6-81947e3f2f78.jpg)
-데이터베이스의 board 테이블 내 데이터들을 tables 페이지에 출력
