### ISSUE TITLE
테스트 시나리오 및 테스트 케이스 안드로이드 조종페이지  동영상 스트리밍

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#43]

**Comment by minsung0628** [comment]
https://1d1cblog.tistory.com/21
- 라즈베리파이 안드로이드 스트리밍

**Comment by jinu12** [comment]
테스트 케이스
![image](https://user-images.githubusercontent.com/73889507/168508414-706f14b4-db81-4a8e-987e-b29710841b3c.png)
https://legendary-open-e74.notion.site/070a490178bf46119f38bce784ebc559?v=076dda4628644f48bcc19e3990acce3f

**Comment by ChaehwanLee** [comment]
refer
- https://rasino.tistory.com/332
- https://projects.raspberrypi.org/en/projects/getting-started-with-picamera/5
- https://www.youtube.com/watch?v=zfBHD4v8hD0
- https://www.youtube.com/watch?v=ll5d342QaCY

**Comment by jinu12** [comment]
테스트 시나리오
1. 웹에서 지역 화면을 스트리밍한다.
2. 지역 라즈베리파이에 라이터로 불을 비추고 버저 센서가 울린다.
3. 웹에서 경고창이 뜨고 삐 소리가 울린다.
4. 웹에서 gps로 경로를 확인한다.
5. 움직여서 화제 지역으로 이동한다.
6. 화제 지역에 이동한후 서브모터로 불이난 방향을 조준한다.
7. 안드로이드 버튼을 눌러서 불이난 지역에 불을 끈다.

**Comment by minsung0628** [comment]
[테스트 케이스.xlsx](https://github.com/fireEmergencyControl/zeroFire/files/8697538/default.xlsx)

**Comment by minsung0628** [comment]
라즈베리 파이를 이용해 앱으로 수중모터 제어 - 완료
서보 모터와 수중모터 동시 제어 - 완료
motion을 이용해서 웹과 안드로이드 앱에 스트리밍 - 완료

**Comment by minsung0628** [comment]
라즈베리파이에서 아날로그 센서 사용 - 수위센서
https://blog.naver.com/PostView.naver?blogId=roboholic84&logNo=220416082742

**Comment by deepDark2** [comment]
일지 작성 페이지 제작

![write page](https://user-images.githubusercontent.com/99372311/168570888-fe55a651-9947-425d-b33a-1c223d86c069.jpg)

-현재 대략적인 틀만 만들어놓은 상태
-추후 구체적인 기능 구현과 DB 구성 예정

**Comment by paramore0** [comment]
![check](https://user-images.githubusercontent.com/99372065/168604364-85f10b8a-6feb-49db-b45d-f3102375767b.png)
불필요한 탭 제거 실시간 카메라 웹,안드로이드 작동 구현
