### ISSUE TITLE
마무리 작업 -- 안드로이드, 웹, 로봇 센서

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#48]

**Comment by jinu12** [comment]
![안드로이드](https://user-images.githubusercontent.com/73889507/168684553-08971088-2c2b-49af-b3c2-736ee95bc9ed.png)
안드로이드 위젯 AppCompat 와 fragment 분리

**Comment by jinu12** [comment]
[zerofile.pptx](https://github.com/fireEmergencyControl/zeroFire/files/8703769/zerofile.pptx)

**Comment by ChaehwanLee** [comment]
Raspberry vnc solution
- https://www.freva.com/how-to-fix-cannot-currently-show-the-desktop-on-raspberry-pi/

**Comment by deepDark2** [comment]
[메인 화면 기능 구현 및 테이블 페이지 수정]

[메인 화면]
-카메라 스트리밍
-센서값 게이지에 표시
-화재 감지시 alert창 표시


![streaming](https://user-images.githubusercontent.com/99372311/168977624-b17a54d5-c2b8-41a9-b1a6-1142f5429e09.jpg)
-동영상 실시간 스트리밍 테스트, 센서와 동시 연동에 성공

![sensor gauge](https://user-images.githubusercontent.com/99372311/168977718-af2bea07-322e-4829-b4a5-7fe0b4744801.jpg)
-센서 게이지 기능 구현

![fire alert](https://user-images.githubusercontent.com/99372311/168977877-bc908f96-31ec-4454-a5b8-8cdd1f07af72.jpg)
-화재 감지시 alert창 표시되는 기능 구현, 추후 디자인 변경 예정

[테이블 화면]
-일지 컬럼 및 값 변경

![tables](https://user-images.githubusercontent.com/99372311/168989789-3604343a-d0d3-4be8-afd5-2b3d14a27c56.jpg)
-요원 번호를 요원 이름으로 변경
-pump상태값을 숫자가 아닌 글자로 알아보기 쉽게 변경
