### ISSUE TITLE
결과 및 ppt 제작

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#52]

**Comment by jinu12** [comment]
지역 라즈베리파이에 라이터로 불을 비추고 부저 센서가 울린다
웹에서 경고창이 삐 소리가 울린다
움직여서 화제 지역으로 이동한다
화제 지역에 이동한후 서브모터로 불이난 방향을 조준한다
안드로이드 버튼을 눌러서 불이난 지역에 불을 끈다
![ezgif com-gif-maker](https://user-images.githubusercontent.com/73889507/169012142-8595754c-8075-4a34-a3a4-9fed1bddafb0.gif)

**Comment by jinu12** [comment]
프리젠테이션 
https://docs.google.com/presentation/d/1G6lDMgiaWgxYc5iaNabY01Y-a8zpMZC7TIcxPYiYN-4/edit?usp=sharing

**Comment by ChaehwanLee** [comment]
refer
- https://deneb21.tistory.com/219 (photo transistor / arduino code and circuit)
- https://blog.daum.net/rockjjy99/249 (Code and circuit)
- https://www.emqx.com/en/blog/use-mqtt-with-raspberry-pi (Raspberry Pi mqtt problem check)
- http://www.steves-internet-guide.com/into-mqtt-python-client/ (Raspberry Pi mqtt problem check)
- https://notstop.co.kr/312/ (Python code 한글 problem solving) # -*- coding: utf-8 -*-

**Comment by deepDark2** [comment]
![fixed alert](https://user-images.githubusercontent.com/99372311/169021647-c8692055-c4ee-49f7-8ddc-3a57310856be.jpg)

-알림창 디자인 변경 완료.

**Comment by minsung0628** [comment]
아두이노 환경에서 gy - gps6mv2(GPS) 동작 확인 - 실내 및 강의실 베란다에선 경도, 위도 가 안 잡힘
라즈베리파이 SPI통신 - (수위 측정 센서, 조도 센서, 불꽃 센서) ----- 결과가 이상함 (강사님과 이야기해본 결과 브레드보드나 점퍼 선등 기기 문제 같같음 라즈베리파이의 다른 장비들을 모두 제거해서 다른 기기의 영향이 없이 실행해야 할 것 같음) 
자동차 영상 촬영
