### ISSUE TITLE
git 규칙, code convention, 템플렛

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#7]

**Comment by ChaehwanLee** [comment]
bootstrap 기본적인 배경 - 간단함
https://startbootstrap.com/theme/sb-admin-2

붉은 배경 UI - 화재예방이라 붉은 배경 찾아봄
https://www.sketchappsources.com/free-source/2758-material-design-ui-kit-sketch-freebie-resource.html

음악 피트니스 - 지도부분에 api 집어넣고 음악재생 부분에 다른 버튼을 넣으면 괜찮아보임
https://www.sketchappsources.com/free-source/1428-spotify-fitness-app-concept-sketch-freebie-resource.html

**Comment by minsung0628** [comment]
https://kmshack.github.io/AndroidUICollection/2017/03/29/CoordinatorTabLayout/ 
- 앱 기본메뉴

https://www.youtube.com/watch?v=vWNrO6k3Y3Q&list=PLz2iXe7EqJOP-HMt6N8d4XoK0zCZAldL6&index=14&ab_channel=%EC%86%8C%EB%86%80%EC%BD%94%EB%94%A9_SonolCoding
 - rc카 조립

https://www.youtube.com/watch?v=HgdoFVd_s4o&list=PLz2iXe7EqJOP-HMt6N8d4XoK0zCZAldL6&index=15&ab_channel=%EC%86%8C%EB%86%80%EC%BD%94%EB%94%A9_SonolCoding
 - rc카 소스업로드& 앱설치

https://www.youtube.com/watch?v=S9-eTwnGMog&list=PLz2iXe7EqJOP-HMt6N8d4XoK0zCZAldL6&index=13&t=31s&ab_channel=%EC%86%8C%EB%86%80%EC%BD%94%EB%94%A9_SonolCoding
- 로봇팔 조립

**Comment by deepDark2** [comment]
bootstrap 테마 선정
https://startbootstrap.com/template/bare
선정 이유 :
 화재 상황에 대한 정보를 한 화면에 표시해
정보 수신이  번거롭지 않게 하기 위함
(화재시 불꽃감지 여부, 카메라 화면, 온도, 가스정보 등을 한 화면에 출력)

https://startbootstrap.com/template/simple-sidebar
선정 이유:
 위의 테마랑 동일한 사유
수신하는 정보를 주제별로 페이지를 나눠서 보거나
추가기능이 필요할 때를 대비한 사이드 메뉴가 존재

**Comment by jinu12** [comment]
https://docs.google.com/document/d/1xxr2f3yGGx7rId-788glnKZvJHw1qTh6U0MxFwSPnmU/edit# 
- 코드 컨베이션
- github 규칙 업로드
### 5. 코드 컨베이션
- 공통
  - 함수명 : 동사 + 명사
  - 변수명 : 명사 + 명사 or 형용사 + 명사
  - 변수 최대 길이 220자
  - 명사는 다수로 쓰지 않되 개수를 나타내는 단어 꼭 적어주기
  - 세미클론, 콤마 뒤에는 공백 ex) print(hi, sendMessage, count)
  - 함수끼리 한줄 개행
  ```pychon
  if(조건식) {
	  조건문
  }

  if(조건식) {
	  조건문
  }

  ```
- 스타일
  - 주석은  한줄 // 회원가입 메소드
- 여러줄 
  /*
  tmap api
    api 주소 및 설정
  */
  
### 6. Github Role
  - 각자 맡은 파일이외의 다른 파일은 건드리지 말 것
  - git pull는 5시에 다 같이 pull
  - git fetch는 pull이 끝나는 즉시 fetch 해서 점검
  - 5시 이외에 pull 한 것 있으면 이슈에 내용을 적고 다음날 9시에 pull하고 fetch
  - commit 타입 
    - feat 새로운 기능 구현
    - add 부수적인 코드 추가, 라이브러리 추가, 새로운 파일 생성
    - chore : 코드 수정, 내부 파일 수정
    - fix : 버그 수정
    - del : 쓸모 없는 코드 삭제
    - style : 코드 형식, 정렬, 주석 등의 변경
    - refactor : 코드 리펙토링
    - test : 테스트 추가, 테스트 리펙토링
    - do;s 문서작성
    - ex) fix (파일이름) -- 회원가입 구현
