### ISSUE TITLE
프로젝트 설계 -웹사이트 요구사항 설계, 웹사이트 프로토타입 설계(오븐), 안드로이드 UI

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#8]

**Comment by minsung0628** [comment]
https://github.com/project-travel-mate/Travel-Mate
- 지도가 있는 앱

**Comment by jinu12** [comment]
![iot 기능 페이지  Untitled](https://user-images.githubusercontent.com/73889507/166423587-066e82e6-e0c7-4e77-bc12-71d16b7d5ff9.jpg)

**Comment by paramore0** [comment]
머큐리앱 - 온습도 표시되어있고 온도 한계치를 설정할 수 있습니다
https://www.instructables.com/IoT-Home-Weather-Monitoring-System-With-Android-Ap/

**Comment by jinu12** [comment]
안드로이드 - https://github.com/project-travel-mate/Travel-Mate 지도 ,전체적인 틀  https://www.instructables.com/IoT-Home-Weather-Monitoring-System-With-Android-Ap/, 컨트롤러 - https://github.com/microsoft/xbox-game-streaming-tools/tree/master/touch-adaptation-kit/samples/sample-layouts

**Comment by ChaehwanLee** [comment]
**mobile 화면**

![fire  차량조정](https://user-images.githubusercontent.com/86588359/166425347-855401ab-c687-4837-aad6-88b660f10bc8.jpg)

![fire  카메라](https://user-images.githubusercontent.com/86588359/166425358-5c9340d7-337a-4cd8-8021-c7a23346d83a.jpg)

![fire  지도](https://user-images.githubusercontent.com/86588359/166425370-68f2fe58-0013-4b35-94e2-ae427092061f.jpg)

**Comment by deepDark2** [comment]
https://ovenapp.io/project/f5awW9lSiCGOOKdkAJ2TuvLhQIb9s32J#H39LN

zeroFire 앱 로그인 초안
![login](https://user-images.githubusercontent.com/99372311/166425610-25dcd5c5-5aaf-4f48-9cc8-28233642ca3e.jpg)

![register](https://user-images.githubusercontent.com/99372311/166425620-3799a75c-c6cc-48c3-af12-f1cfc46f8b9f.jpg)
