### ISSUE TITLE
mqtt 테스트, 웹 - 안드로이드 프론트엔드

### ISSUE THREAD

**Issue by jinu12** [fireEmergencyControl/zeroFire#9]

**Comment by jinu12** [comment]
<a href="https://github.com/fireEmergencyControl/zeroFire/pull/10/commits/d3903eb5d7b37109466819783f6ac88475d49d98" 프로젝트 초기 설정 - 웹> </a>
<a href="https://github.com/fireEmergencyControl/zeroFire/pull/11">프로젝트 초기 설정 -안드로이드, mqtt, 아두이노 </a>

**Comment by jinu12** [comment]
<a href="https://github.com/fireEmergencyControl/zeroFire/pull/12">웹 register url 추가 </a>

**Comment by jinu12** [comment]
웹 메인 페이지
![web mainpage 현황](https://user-images.githubusercontent.com/73889507/167366494-9173518c-435f-49eb-b243-227fd330e4bd.PNG)

**Comment by ChaehwanLee** [comment]
pi arm 참고자료 search

- https://github.com/custom-build-robots/6-Axis-Desktop-Robotic-Arm-Raspberry-Pi

- https://www.waveshare.com/wiki/Robot_Arm_for_Pi

**Comment by deepDark2** [comment]
웹 페이지 등록 화면 구성
![오늘 한 일](https://user-images.githubusercontent.com/99372311/167367200-f90ed7b7-decf-480b-90f2-ba31799a5d0a.jpg)

**Comment by paramore0** [comment]
![kkb11](https://user-images.githubusercontent.com/99372065/167367571-6a427d68-53ec-4d94-96fc-130ff472c12f.png)
